### ISSUE TITLE
Add links to QSS docs into README

### ISSUE THREAD

**Issue by ghost** [ZoomTen/olive-themes#2]
- https://doc.qt.io/qt-5/stylesheet.html
  - https://doc.qt.io/qt-5/stylesheet-syntax.html
  - https://doc.qt.io/qt-5/stylesheet-reference.html
  - https://doc.qt.io/qt-5/stylesheet-examples.html
- https://doc.qt.io/qt-5/stylesheet-designer.html
- https://doc.qt.io/qt-5/stylesheet-customizing.html
- https://doc.qt.io/qt-5/qtwidgets-widgets-stylesheet-example.html

**Comment by ZoomTen** [comment]
Added except for [this](https://doc.qt.io/qt-5/qtwidgets-widgets-stylesheet-example.html), which seems to be a guide on application side implementation.
